/*
 * ADC_Config.h
 *
 *  Created on: Nov 22, 2021
 *      Author: amgdRaghed
 */

#ifndef MCAL_ADC_CONFIG_H_
#define MCAL_ADC_CONFIG_H_

/*	ADC REFERENCE VOLATGE Options:
 *	1- ADC_AVCC_REFERENCEVOLATGE
 *	2- ADC_INTERNAL_REFERENCEVOLATGE
 */

#define ADC_SET_REFERENCEVOLATGE  ADC_AVCC_REFERENCEVOLATGE

/*	ADC Prescaler options:
 * 	1- ADC_2_PRESCALER
 * 	2- ADC_4_PRESCALER
 * 	3- ADC_8_PRESCALER
 * 	4- ADC_16_PRESCALER
 * 	5- ADC_32_PRESCALER
 * 	6- ADC_64_PRESCALER
 * 	7- ADC_128_PRESCALER
 */
#define ADC_SET_PRESCALER   ADC_128_PRESCALER

/*	ADC Adjust Options:
 *	1- ADC_LEFT_ADJUST
 *	2- ADC_RIGHT_ADJUST
 */

#define ADC_SET_ADJUST  ADC_RIGHT_ADJUST

#endif /* MCAL_ADC_CONFIG_H_ */
